### ISSUE TITLE
[Bug] Trailing slash in host isn't always stripped out

### ISSUE THREAD

**Issue by nemchik** [LunaTools/LunaSea#204] opened 2020-04-25 17:47 UTC
> Developer Note: The user found the solution by removing the trailing `/` from their host. LunaSea *should* be stripping/trimming the host, but it didn't work in this case so I need to investigate that logic.

**Describe the Bug**
I'm not seeing any images (banners) for anything in Sonarr or Radarr. If I'm supposed to see images anywhere else in the app I'm not seeing them either. I'm have NZBHydra2 and NZBGet setup as well.

**To Reproduce**
Open the app. Look anywhere there should be banners or images (the screenshots on the LunaSea website show banners for shows and movies). I'm not seeing them.

**Expected Behaviour**
I'd like to see banners and images.

**Screenshots**
Skipping for now.

**Versions**
LunaSea Version: 2.1.0 (66)
Radarr Version: 3.0.0.2871-ls5 by linuxserver.io (docker)
Sonarr Version: 3.0.3.770-ls9 by linuxserver.io (docker)

Phone: Motorola moto z3 (Moto Z(3))
Android Version: 9 (28)
Device (product): messi (messi_verizon)
Rom: PDX29.84-51-11

**Additional context**
I'm accessing through reverse proxies.

**Comment by JagandeepBrar** [comment] 2020-04-25 22:05
Did you disable SSL authentication in the settings or have any custom authentication enabled?

**Comment by nemchik** [comment] 2020-04-25 22:31
> Did you disable SSL authentication in the settings

No. But since you mention it I tried it just now. It doesn't seem to make a difference when it's on or off. I've set it back to on since that's how it was originally.

> or have any custom authentication enabled?

No. Here are the proxy configs I'm using:

https://github.com/linuxserver/reverse-proxy-confs/blob/master/sonarr.subfolder.conf.sample
And
https://github.com/linuxserver/reverse-proxy-confs/blob/master/radarr.subfolder.conf.sample

I haven't modified the files, they run exactly as they appear in those links.

**Comment by JagandeepBrar** [comment] 2020-04-25 23:09
Can you try removing the second blocks which are redirecting the API routes?


`location ^~ /sonarr/api { ... }`

And 


`location ^~ /sonarr/api { ... }`

If that still doesn’t work, would you be comfortable sending at least one for your host + API key configurations? I am not able to reproduce it locally, so being able to see exactly what error is thrown will help pinpoint the issue.

**Comment by nemchik** [comment] 2020-04-25 23:18
> Can you try removing the second blocks which are redirecting the API routes?
> 
> `location ^~ /sonarr/api { ... }`
> 
> And
> 
> `location ^~ /radarr/api { ... }`

I tried it, and it didn't make a difference. BTW those second locations are there for the purpose of allowing API access without any extra auth that might be added to the top location (to protect the web UI).

I'll email you an API key shortly.

**Comment by nemchik** [comment] 2020-04-26 02:18
I figured it out!

I was including a trailing slash in the URL I was entering in LunaSea. Removing the trailing slash resolved the issue.

I mentioned in my email that I setup a second instance of sonarr, and I did not realize I had forgotten the trailing slash when setting up the second profile in LunaSea.

Somehow everything worked with the trailing slash except images and banners. Maybe this could be looked into more? Like trim the trailing slash automatically?

**Comment by nemchik** [comment] 2020-04-26 02:20
P.s. with that, I'm going to reset my API key. Hopefully it's not needed anymore.

**Comment by JagandeepBrar** [comment] 2020-04-26 02:55
Thanks for getting back to me with a solution, I didn't have a chance to touch your instance anyways, but yes you're good to reset it now!

I'll keep this issue open and continue looking into it, it does (or rather should) trim a trailing `/`, but clearly it didn't work for you in this case and so I'll have to see what might be causing it.

By any chance, do you remember if you had a trailing space after the ending `/`?

**Comment by nemchik** [comment] 2020-04-26 03:16
> By any chance, do you remember if you had a trailing space after the ending `/`?

Nope, there definitely wasn't.

I tested just now and was able to put the trailing slash back in. Connection test succeeded.

I then added a space after the trailing slash. Connection test succeeded.

I didn't check to see if banners would break when doing this (figured they might be cached).

**Comment by JagandeepBrar** [comment] 2020-07-11 18:15
This has been fixed in https://github.com/LunaTools/LunaSea/commit/9736ab6b00fb04948763f96613504909e51688c4, and will be in the next TestFlight release/v3.1.0.

**Closed by JagandeepBrar** 2020-07-11 18:15 UTC
Labels: bug
